### PR TITLE
Fixed all typos and broken links

### PR DESCRIPTION
**Pull request by lesleyrs**
Hey good job on this. Just read through the entire thing ahead of https://github.com/ISSOtm/gb-asm-tutorial being finished. I managed to find a replacement for all broken links and I believe I found all typos.

### CODE REVIEW

**Comment by ahrnbom** [comment]
Thanks for this! Let me take a look at your changes :)

**Comment by lesleyrs** [comment]
I just noticed Github isn't showing all diff highlights correctly on web? Strange

**Comment by ahrnbom** [comment]
I also noticed this, but don't worry about it; I'll just run diff locally. So you'll have to wait until I have some time to sit at a computer :)

**Comment by ahrnbom** [comment]
Hi! I finally took the time to look through this. Sorry for the delay!

The `sufficient detail` vs `sufficient enough detail` thing, while both of them work, neither is ideal. Can we change it to `sufficient level of detail`?

Your change under "Making Game Boy games" is wrong, instead it should say something like "other pieces of hardware, responsible for making graphics and sound, and interpreting input". The word "means" makes it even more unclear than it already was, IMO.

The `so some interrupt handling code` is also wrong, this was not a typo. It refers to a specific code.

As for changing GPU to PPU, this change would need to include a brief explanation of what the PPU is. This is a book for game developers familiar with modern programming; we can expect them to know what a GPU is, but not a PPU. Simply explaining that the PPU is the Game Boy's variant of a GPU should be sufficient.

Other than that, all your changes are correct and appreciated!

**Comment by lesleyrs** [comment]
> Your change under "Making Game Boy games" is wrong, instead it should say something like "other pieces of hardware, responsible for making graphics and sound, and interpreting input". The word "means" makes it even more unclear than it already was, IMO.

I didn't change it because it was unclear, but I think `that make ...` isn't proper English? Not a native speaker though. I didn't want to change it too much but `that means`, `that makes` or `that consists of` all sound better IMO but I reverted it.

Agreed with all others and I added the changes, if you still want to change something you have write access to my repos master branch.

**Pull request merged**
